// 2/React_demo/src/components/Login/Login.tsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../../context/AuthContext";
import { Container, Form, Button, Alert } from "react-bootstrap";

function Login() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const { login } = useAuth();
  const navigate = useNavigate();

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (login(username, password)) {
      navigate("/people");
    } else {
      setError("Invalid username or password.");
    }
  }

  return (
    <Container style={{ maxWidth: "400px", marginTop: "80px" }}>
      <h2>Login</h2>
      <p className="text-muted">
        Demo credentials: <strong>admin</strong> / <strong>password</strong>
      </p>

      {error && <Alert variant="danger">{error}</Alert>}

      <Form onSubmit={handleSubmit}>
        <Form.Group className="mb-3" controlId="username">
          <Form.Label>Username</Form.Label>
          <Form.Control
            type="text"
            placeholder="Enter username"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
          />
        </Form.Group>

        <Form.Group className="mb-3" controlId="password">
          <Form.Label>Password</Form.Label>
          <Form.Control
            type="password"
            placeholder="Enter password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
        </Form.Group>

        <Button type="submit" variant="primary" className="w-100">
          Login
        </Button>
      </Form>
    </Container>
  );
}

export default Login;

// 2/Angular_demo/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  username = '';
  password = '';
  error = '';

  constructor(private authService: AuthService, private router: Router) {}

  onSubmit() {
    if (this.authService.login(this.username, this.password)) {
      this.router.navigate(['/']);
    } else {
      this.error = 'Invalid username or password. (Hint: admin / password)';
    }
  }
}

<section class="auth-page">
  <div class="auth-card login-card">
    <h2 class="auth-title">Login</h2>
    <p class="auth-subtitle">Sign in to continue.</p>

    <div *ngIf="error" class="message-error">{{ error }}</div>

    <form class="auth-form" (ngSubmit)="onSubmit()">
      <div class="form-field">
        <label class="form-label" for="username">Username</label>
      <input
        class="form-input"
        id="username"
        type="text"
        [(ngModel)]="username"
        name="username"
        placeholder="Enter username"
        required
      />
      </div>

      <div class="form-field">
        <label class="form-label" for="password">Password</label>
      <input
        class="form-input"
        id="password"
        type="password"
        [(ngModel)]="password"
        name="password"
        placeholder="Enter password"
        required
      />
      </div>

      <button class="button-primary" type="submit">Login</button>
    </form>

    <p class="auth-note">Demo credentials: <strong>admin</strong> / <strong>password</strong></p>
  </div>
</section>
